<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RollForward>Major</RollForward>
		<Product>[QuickProtocol]测试客户端</Product>
		<AssemblyTitle>[QuickProtocol]测试客户端</AssemblyTitle>
		<Authors>scbeta</Authors>
		<Version>2.9.3</Version>
		<IsPackable>false</IsPackable>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<Description>用于测试连接到[QuickProtocol]服务端的客户端。
项目地址：https://github.com/QuickProtocol</Description>
		<Copyright>Apache License</Copyright>
		<PackageProjectUrl>https://github.com/QuickProtocol</PackageProjectUrl>
		<RepositoryUrl>https://github.com/QuickProtocol/QuickProtocol_CSharp</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Images\connection.ico" />
		<None Remove="Images\ilQpInstructions.Images.0.png" />
		<None Remove="Images\ilQpInstructions.Images.1.png" />
		<None Remove="Images\ilQpInstructions.Images.2.png" />
		<None Remove="Images\ilQpInstructions.Images.3.png" />
		<None Remove="Images\ilQpInstructions.Images.4.png" />
		<None Remove="Images\logo-large.png" />
		<None Remove="Images\logo.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Images\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.3" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.3" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Quick.Protocol.Pipeline\Quick.Protocol.Pipeline.csproj" />
		<ProjectReference Include="..\Quick.Protocol.SerialPort\Quick.Protocol.SerialPort.csproj" />
		<ProjectReference Include="..\Quick.Protocol.Tcp\Quick.Protocol.Tcp.csproj" />
		<ProjectReference Include="..\Quick.Protocol.WebSocket.Client\Quick.Protocol.WebSocket.Client.csproj" />
		<ProjectReference Include="..\Quick.Protocol.Http.Client\Quick.Protocol.Http.Client.csproj" />
		<ProjectReference Include="..\Quick.Protocol\Quick.Protocol.csproj" />
	</ItemGroup>

</Project>
